### ISSUE TITLE
animation, 화면전환 효과 등 추가

### ISSUE THREAD

**Issue by qqq1212341** [kucc/KUCheckCheck#38]
# 설명
1. react-spring 등 라이브러리 사용하여, 메인 페이지에서 코스가 여러 개일 때 필치면 spring 애니메이션이 출력되도록 한다.
2. 코스 상세페이지에서 코스 출석 페이지로 넘어갈 때 화면 전환 효과 추가하기( react-spring으로 구현 가능)
3. courseContainer에서 마우스 hover 했을 때 그림자 색이 바뀌는 등의 효과 추가하기

### ToDo
- [x] 메인 페이지에서 spring 애니메이션
- [x] 코스 상세페이지 화면 전환 효과
- [x] 마우스 hover 시 색 전환
